### ISSUE TITLE
add token_pool_* documentation lines back to combined token.h

### ISSUE THREAD

**Issue by DivineDominion** [fletcher/MultiMarkdown-6#103]
The exported `token.h` in the libMultiMarkdown framework has this at the top:

```
#ifdef kUseObjectPool
void token_pool_init(void);				//!< Initialize object pool for allocating tokens
void token_pool_drain(void);			//!< Drain pool to free memory when parse complete
void token_pool_free(void);				//!< Free the token object pool
#endif
```

The documentation comments are being stripped here, unlike other functions of the same origin header:

```
/// Duplicate an existing token
token * token_copy(
	token * original					//!< Token to be copied
);
```

## Expected Result

This would add a bare minimum doc-string back to the resulting framework:

```
#ifdef kUseObjectPool
/// Initialize object pool for allocating tokens
void token_pool_init(void);

/// Drain pool to free memory when parse complete
void token_pool_drain(void);

/// Free the token object pool
void token_pool_free(void);
#endif
```

**Comment by fletcher** [comment]
Not sure I follow what the problem is.

**Comment by DivineDominion** [comment]
Mostly the Xcode quick help/code documentation feature. Whatever `//!<` is, it's not recognized, so you end up with functions that you don't know how to use unless you look at the source.

**Comment by fletcher** [comment]
That formatting is for doxygen.

**Comment by DivineDominion** [comment]
I saw this was used for function parameter documentation, so I was puzzled why the comment "type" changed here. Ah well, so we cannot have it like in all the other places, with `///` instead you say?

**Comment by fletcher** [comment]
All of the comment documentation is for doxygen.  I have not looked at what xcode does with it.

For those three functions in particular, the less well documented they are the better.  For most uses of MMD as a library in another app, you should strongly consider the implications of using "token pools" and how you plan to do memory management.  If you're simply compiling MMD as is, then use them to get more performance when processing large files.  For everything else, they should probably be disabled until one truly understands what is happening behind the scenes.

If you are still working on a syntax highlighting app, that implies you need access to the token tree outside of libMMD.  Which implies the tokens need a lifespan that exceeds the function call in which they were created.  Which means libMMD is unable to determine when it is safe to drain the pool, leading to one of three scenarios:

1. The pool is never drained, meaning there will be ongoing memory leaks.

2. The pool is drained while tokens are still in use, leading to memory errors attempting to access memory that has been (potentially) rewritten and no longer makes sense.  Depending on your machine, it may take a while to see the effects of these errors, but it's a matter of time.

3. You spend a fair amount of time carefully designing a system of draining the token pools properly, probably meaning that your application is only capable of doing one thing at a time that involves libMMD, and you scratch out a bit of extra performance that most users will never notice at the expense of a more complicated (and possibly more fragile) program that took a fair amount of man-hours to develop and test.

(There's always the possibility of option 4 that I missed that involves finding the easy, perfect solution to all of the above...  But I haven't thought of it yet.  ;)

**Comment by DivineDominion** [comment]
These are good points and you're right, I figured the memory management using token pools does not suit my highlighter at all :) 

When the functions are part of the published API, I think it'd be super helpful to have inline documentation in Xcode. (Which is just what you have written in the original headers; the format weirdly changes during the Cmake process, so I thought this is not intended.) If you rather have people not use it at all -- instead of wrongly, which I initially did --, wouldn't it make sense to remove these functions from the public header?

As you probably have noticed, I fiddled with the MMD6 highlighter today :) I noticed that `mmd.h` is not among the copied headers and the `mmd_engine` struct's capabilities thus are only exposed as a generic pointer type. (`OpaquePointer` in Swift) I didn't know this would happen before I encountered it, but this is effectively another way to have information hiding. 

What about a `token_public.h` that does not expose the token pool stuff for regular Joes and Janes?

**Comment by fletcher** [comment]
I think I'm only understanding part of what you're saying...

1. The "published API" (if such a thing exists), is `libMultiMarkdown.h`.  **Most** people who are using MMD to convert text to HTML only need the functions here, and therefore only need this single header file.  It's designed that way on purpose.  

2. If you're getting into the "next level", such as writing a syntax highlighter, you probably need access to the `token` data type struct, so including `token.h` may be necessary.  But you probably only need the struct definition and the `token_tree_free()` function, unless you're getting into some fancy stuff.  If you're doing enough to need to use tokens directly, I hope you read the part of `libMultiMarkdown.h` file that tells you not to use with token pools unless you know what you're doing.  ;)  Sure --  a `token_public.h` file is possible, but I'm not sure it's really worth complicating things by adding it.  By the time you really need to use tokens, you should know what you need to do with them and what you don't.

3. Depending on how you're handling "mutable" c-strings, you might find the `d_string.h` functionality helpful.  It's a really a separate library (I use it all over the place in my software), so it's not included in the main header file.  But it's also something that most people won't need.

4. That's why those three files are exposed as public headers in the CMake configuration (along with `version.h`).  Unless you're working on MMD itself, you shouldn't need the other files directly.  Of course, they're there if you need them.  Those are the main files I use in MultiMarkdown Composer, for example.   I use `stack.h`, but that is because I have some other routines I run, and `stack`s are much like `d_string`s and used in a lot of my code for convenience.  I also use `transclude.h` to expose some functionality in one or two specific places.

5. I don't understand what you mean about Cmake changing formatting.  I'm not aware of CMake modifying any of the files, except for `version.h`.  Maybe I'm forgetting something?

6. `mmd_engine` is designed as an "opaque" object.  It should be used via the "API" in `libMultiMarkdown.h`, but as the whole project is open source, one can, of course, do whatever one likes.

**Comment by DivineDominion** [comment]
Thanks a ton for the clarification! 

- I found I needed to import `mmd.h` because I wanted access to the engine's `root` token, reusing the engine and its underlying `DString`. Only then did I understand that once I rely on `root`, the approach is wrong, because parsing always free's the cached root token tree. (Was parsing the whole doc for convenience and wondered why I could not access the result.) The `libMultiMarkdown.h` header sure is enough to achieve what I need to do.

- (5) I was mistaken about Cmake changing formatting. I looked at `token.c` and found the `///`-prefixed comments, so I wrongly inferred something was happening during the automated process.

Since you said not exposing the doxygen stuff to Xcode is on purpose, I'll close the issue.
