### ISSUE TITLE
Superscript special character parsing

### ISSUE THREAD

**Issue by geranyl** [fletcher/MultiMarkdown-6#105]
Superscript using the ^character^ format does not parse special characters such as addition signs unless proceeded by a letter or number. E.g. Na^1+^ will parse correctly, however Na^+^ does not. 

Interestingly it parses just fine if the superscript occurs within a table layout.

**Comment by fletcher** [comment]
1. The table issue is actually a separate bug that prevented MMD from properly descending into tables to assign "ambidextrous" tokens the ability to open/close a pair.  This lead to each token being able to open and close a pair, making it *seem* to work "properly" here.  That issue is now fixed.  (Thanks for mentioning this!)

2. I adjusted the algorithm to allow initial punctuation characters in the paired superscript syntax.  Thanks for this as well!
