### ISSUE TITLE
32bit version doesn't work!

### ISSUE THREAD

**Issue by guest482** [fletcher/MultiMarkdown-6#113]
I get this error after removing 32bit 5.4.0 and installing 32bit 6.3.0:
Program 'multimarkdown.exe' failed to run: The specified executable is not a valid application for this OS platform.

When I reinstall 5.4.0, the problem goes away. Thanks

**Comment by fletcher** [comment]
I don't have a convenient means of testing this.  The 32-bit version is included "just because", but if it no longer works I can stop including 32-bit builds for new releases.  If it doesn't work, then I would recommend compiling from source on the target OS/machine.

Can also try other 32-bit builds for v6 to see if any of those work.

**Comment by guest482** [comment]
Installed 6.0.7 32 and it works fine.
Is it possible the 6.3.0 32 is accidentally the 6.3.0 64?
Unfortunately I am unable to do my own builds! May I request another 32 build just in case ?

**Comment by fletcher** [comment]
I pushed another 32-bit .exe build to the release. It may be that the last one was the 64 bit version, since the file sizes are off by only a few bytes.
