### ISSUE TITLE
cross compiling for djgpp

### ISSUE THREAD

**Issue by jlrn7** [fletcher/MultiMarkdown-6#119]
Hello! I was trying to cross-compile mmd6 for dos, using the djgpp backend on cygwin64. Omitting `#include <libgen.h>` on line 57 of `main.c` doesn't seem to be an issue, but I found a dependency on the `warnx()` function in `argtable3.c` lines 358 ff. Since the `err.h` header is missing on djgpp, and thus the function is missing, compilation fails. How can I provide the function for the djgpp compiler to work?

**Comment by fletcher** [comment]
You would need to talk to the author(s?):

https://github.com/argtable/argtable3

Or you can just include the `err.h` header.

**Comment by jlrn7** [comment]
Let me see if I got this straight: `argtable3` is yet another library, so I should build/install it for my target platform, correct?

**Comment by fletcher** [comment]
It's a single (well, double) file library, so it's just included statically.  But if the problem is missing err.h, just provide `err.h` and `err.c` from somewhere and see if it works.  You might have to keep following the dependencies, but it's worth a try.

Or replace the `warnx()` function if that's the problem.

**Comment by jlrn7** [comment]
How do i add a dependency on the err.obj from within cmake? I did compile it commenting out the calls to `warnx()`, but that's dirty. I'm a total newbie on cmake. A link may also work.

**Comment by fletcher** [comment]
I would need more information.  I have not gotten any other reports of MMD failing to run on Windows in recent versions (6.0.3 is pretty old).

**Comment by jlrn7** [comment]
I don't know what to add. On Windows (32 and 64 bits), and the DOSBox emulator (djgpp port), mmd6 dies silently and goes to freeze: on Windows it freezes the system; on DOSBox it freezes the emulator, so the process must be killed manually, from without. However, on freedos, my djgpp port dies gracefully stating "No swap space!" At some other point in the debugging process it died gracefully stating "Swap disk full!" So the failure does not seem to depend on the OS. So my best guess is that somewhere there is a massive memory leak. Again, it crashes so miserably that there is little room for debugging: no time for memory dumps or anything like that.

**Comment by fletcher** [comment]
If there's a memory leak like that, it would seem to come from something you changed???  I have tested extensively for memory leaks throughout development.  It's possible something crept in during a recent bug fix that, but not likely.  And certainly not to the extent that should cause a crash.  And, as stated, other Windows users have not had trouble (except for CJK file names, but that's a separate Windows issue).

You can try disabling tokenpools if you are running on a severely limited machine, as it allocates larger chunks of memory at once, rather than a single token at a time.  But we're talking several kilobytes of RAM in each block, not gigabytes.  If that's causing the problem, you will have bigger issues.

**Comment by jlrn7** [comment]
Well, just for the record: I only tried to compile 6.3.2 by myself, for all PC platforms (freedos and windows) by cross-compiling on Cygwin. I tested all other versions from the distros provided at GitHub: that's how I detected that failure began on 6.0.3; and my machine is a state of art Windows 10-64, running on an Intel64. 

If you can't reproduce the bug, then I fear now it's time to make effective the (lack of) warranty (T_T)

**Comment by fletcher** [comment]
It comes with a double your money back refund of the purchase price.  ;)

What happens if you compile the recent version on Windows as-is (I know you have to modify it for DOS)?

Also, because people have tried, *cough*, "less than ideal approaches to using the software" -- how, exactly, are you determining that the MMD doesn't work?

**Comment by jlrn7** [comment]
Turned out that the problem was a faulty source file. What construct exactly mmd6 choked on is still to be determined, but current version (6.3.2) has been passing tests consistently. However, I made a test with the `README.md` file from the main page of this project, and beginning version 6.0.3, mmd6 began to fail, as reported earlier. Apparently, mmd6 tries to parse something from `readme.md` and fails to do so. but that's another issue.

So I will make a fork and add the code fixing the issues I found while porting mmd6 to msdos/djgpp for you to see. I am still in the dark about how to define flags for the compiler to enable conditional compiling as required, so I trust you'll tell me how to configure cmake to do so.

**Comment by fletcher** [comment]
I built from tag `6.0.3` and from latest develop commit, and neither gave me any trouble with the `README.md` (also either from the `6.0.3` commit, or from develop).

If you are able to narrow anything down on that, definitely let me know.

**Comment by fletcher** [comment]
As to CMake - an example is the `TEST` flag.  It's defined in the `Makefile`, and then used in the `CMakeLists.txt` file, along with an example of the `if..then` syntax.

**Comment by jlrn7** [comment]
Worked like a charm. I'll make some regular tests on different platforms before committing the patches to the branch. Thanks.

As for the failure on my test file, I'll get back to that later.

**Comment by jlrn7** [comment]
I figured out a way to compile for msdos-djgpp; I'm opening a branch with changes for revision.
