### ISSUE TITLE
Sequential quotation paragraphs become separate quote environments

### ISSUE THREAD

**Issue by ipetraka** [fletcher/MultiMarkdown-6#122]
In MMD5, and in a fashion that I believe is fairly consistent across other Markdown engines and treatment of sequential elements within MMD, the following text would produce an homogenous quotation environment:

```Markdown
> Paragraph one.

> Paragraph two.
```

HTML Output:

```html
<blockquote>
<p>Paragraph one.</p>
<p>Paragraph two.</p>
</blockquote>
```

LaTeX Output:

```latex
\begin{quote}
Paragraph one.

Paragraph two.
\end{quote}
```

Etc.

With MMD6, we are now getting separate quotation environments for *each* paragraph, which isn't best practice in terms of semantics:

```html
<blockquote>
<p>Paragraph one.</p>
</blockquote>

<blockquote>
<p>Paragraph two.</p>
</blockquote>
```

```latex
\begin{quote}
Paragraph one.
\end{quote}

\begin{quote}
Paragraph two.
\end{quote}
```

True, if one puts a "glue" line between each paragraph, in the same way an email might, then the result is expected. For example:

```Markdown
> Paragraph one.
>
> Paragraph two.
```

However, like I say, that is not consistent with how sequential elements work elsewhere, and in my opinion it's not a "nice" look, nor is it easier to type and edit around that approach.

To compare with another element that supports sequential use, one does not need to do the following---and indeed if you try you will break syntax:

```
Definition Term
: Definition line one.
:
: Definition line two.
```

**Comment by fletcher** [comment]
This is a change in MMD-6, based on how faster parsers can be implemented, and is consistent with other changes in MMD-6, as well as with the CommonMark spec.  I am not saying that I will 100% follow the CommonMark spec, but it is one thing I consider in potentially ambiguous situations.

There are many things those behind CommonMark did wrong, but many things they did right.  This is one that I *think* is more towards right than wrong, based on having a standardized approach to how blank lines reset sequential items that could be continuations or could be separate elements and allowing authors to specify which of two ambiguous interpretations was meant.  

(Short technical backstory -- I think that part of the problem with Markdown 10+ years on is that it was designed using a mess of regexp substitutions without any concept of a formal grammar/parser.  This lead to many edge cases in Markdown.pl that have never, and likely will never, be fixed.  And since Markdown.pl is the de facto spec, that means the spec is ambiguous. The CommonMark project sometimes swings "too far" the other way, with having a very well defined spec, that on rare occasions parses seemingly obvious (to a human) structures by following that spec.  While true that a PEG can reasonably accurately match some of the edge cases of Markdown.pl, it does so at a fairly steep cost in terms of speed.  CommonMark and MMD-6 are both written for performance, and one of the ways to do that is to minimize having to backtrack and parse the same section of text more than once.  Part of this process is that blank lines generally (but not always) "reset" the parser state resulting in some split structures, like blockquotes.)

A counter-example, however, is indented code blocks:

	Plain text

		test

		two

Even in CommonMark, this will be treated as a single code block following a plain text paragraph, not two separate code blocks.

In this case:

1. Yes, it's a change.

2. As you point out, there is a mechanism for the author to resolve the ambiguity and specify whether they desire a single blockquote with two paragraphs, or two separate blockquotes.  

3. I am inclined to stick with CommonMark on this (at least for now).  Honestly, most Markdown implementations are not particularly well-written and have terrible edge case performance in a wide range of situations.  In general, CommonMark does a great (but not perfect) job with this.  I have tried to pay similar attention to edge cases and consistency in MMD-6, and alignment with CommonMark is one of many criteria I use.  I will sometimes "poll the group" using Babelmark to look for overwhelming consensus, but pay little attention to most specific implementations.  (In this case, it's roughly a 50/50 split)

4. In instances where I do disagree with CommonMark's implementation, I make sure that I have a well-defined reason, and discuss that with MacFarlane.  The main instance so far was strong/bold parsing.  CommonMark has a well-defined algorithm for parsing these, but it misses some edge cases that don't fit the rules well.  I discussed my thoughts with John, but he preferred to stick with his existing spec.  I agree that the edge cases are rare, and even MMD-6 misses some of them.  Otherwise, I think I have sided in agreement with CommonMark on most of the other situations, except where they clearly had to change because of some other feature in MMD that doesn't exist in Markdown itself.

5. If the CommonMark interpretation of this situation changes, then I would be willing to change MMD-6 to coincide (barring technical limitations.)  But given that it is specifically pointed out as an example where CommonMark chooses to differ from Markdown.pl, my *guess* is that won't happen.  <https://spec.commonmark.org/0.28/#example-205>
