### ISSUE TITLE
Latex output: special characters in links aren't properly escaped

### ISSUE THREAD

**Issue by jlargentaye** [fletcher/MultiMarkdown-6#124]
The following markdown file generates incorrect Latex, using mmd from branch develop commit 7853915:

```
Title:	Link Variations
latex config:	article

Reserved characters in Latex:

& %  # _ { } ~ ^ \

[Simple Link](http://example.com/simple)

[& link](http://example.com/&foo=bar)

[% Link](http://example.com/%25%20link)

[# link](http://example.com/#foo)

[_ link](http://example.com/_foo)

[~ link](http://example.com/~foo)
```

I have limited the link tests to those characters I have seen in URLs (I am not a web developer), and assume the others should usually appear URL-escaped, as in the %-example.

**Comment by jlargentaye** [comment]
Ah, my issue was that the generated latex failed on the special characters in the produced \href{}, but apparently this was caused by me using outdated latex support packages (from https://github.com/fletcher/peg-multimarkdown-latex-support). This was fixed by switching to the updated mmd6-memoir-book support files.

I guess the newer Latex packages better support special characters in \href{} ?

**Comment by fletcher** [comment]
No idea...  ;)

Much of my LaTeX knowledge is on a need-to-know basis.  When I need it, I figure it out or research it.  Then I tend to let it slide to the background.  I did a great deal of LaTeX work while developing MMD, but since then have needed it less and less since I can use straight MMD more and more.  Which was the purpose....  ;)

But if you find something else that is broken in latest version (development branch), the definitely let me know and I can keep looking.
