### ISSUE TITLE
Curly Brackets in LaTeX-Lists

### ISSUE THREAD

**Issue by mrkwnzl** [fletcher/MultiMarkdown-6#128]
Hello,

when I create a list in MMD6 and export it to LaTeX, the items have curly brackets appended. For example:

MMD:
```
- Item 1
- Item 2
```
Export in LaTeX:
```
\begin{itemize}
\item{} Item 1
\item{} Item 2
\end{itemize}
```
This doesn’t seem to be a problem *per se*, but I use the label argument in LaTeX lists in oder to label the list items, like so:

MMD:
```
- [A.] Item 1
- [B.] Item 2
```
LaTeX export with MMD5 gave this, which worked just fine:
```
\begin{itemize}
\item [A.] Item 1
\item [B.] Item 2
\end{itemize}
```
But MMD6 export delivers this, with which the label does not work in LaTeX:
```
\begin{itemize}
\item{} [A.] Item 1
\item{} [B.] Item 2
\end{itemize}
```

In the change log I found this entry (2017-03-05 -- v 0.4.2-b):
> FIXED: latex list items need to block optional argument to allow '[' as first character.

If this has been changed in order to allow “[” as the first character in a list, I’d suggest the route of escaping the first square bracket in lists, like we do with all square brackets that could be mistaken for syntax. Especially as it seems that `\item{}` is not proper LaTeX syntax (I could be mistaken on this, but I found no reference to curly brackets behind `\item` anywhere).

Thanks a lot!

**Comment by mrkwnzl** [comment]
That’s really a shame. I really liked that. But this seems to be an inherent problem with LaTeX, rather than an MMD issue. For example, in LaTeX it’s also not possible to simply start a list with a `[`. What can be done is to put anything in square brackets also in curly brackets.

So if you want a list item start with a square bracket, here is what one could do in LaTeX:
```
\begin{itemize}
\item {[Item in Square Brackets]}
\end{itemize}
```
This could be achieved in MMD5. Easy and consistent with LaTeX syntax.
```
- {[Item in Square Brackets]}
```

In HTML, this is not an issue either way. HTML renders the square bracket without issue. So it seems to only impact LaTeX. Is that correct?

So I guess what I’m proposing is to revert it back to the way it was. Everyone who needs a square bracket at the beginning of a list item can use curly brackets, just like in actual LaTeX.

Here’s my argument:

I lose an important, very easy possibility of using MMD to have lists in LaTeX with individual labels for every item and even make it a nested list. This can even with the extensive tools in Scrivener not be replicated, as far as I can see. I absolutely need to use raw LaTeX for this.

On the other hand, whoever needs a square bracket at the beginning of a list in LaTeX needs only to set in inside curly brackets. That’s simple.

Here’s a real world example from my master thesis:
```
- [w~1 =] **Fiction world (@):**
    - [(1)] Sherlock Holmes does not exist.
    - [(2)] Arthur Conan Doyle is the author of the fictional cases of Sherlock Holmes.
```
That’s a pretty easy and most importantly *readable* way to achieve this in LaTeX:
```
\begin{itemize}
\item [$w_{1}$ =] \textbf{Fiction world (@):}
\begin{itemize}
\item [(1)] Sherlock Holmes does not exist.
\item [(2)] Arthur Conan Doyle is the author of the fictional cases of Sherlock Holmes.
\end{itemize}
\end{itemize}
```
And this needs to be repeated three times in my thesis for this example alone. What I’m trying to say is, I think the trade-off for people who need square brackets at the beginning of list items is rather small. They gain little, I lose very much.

And I’m sorry for this wall of text. It’s just something that made my life immensely easier, so it’s a thing of passion for me.

**Comment by fletcher** [comment]
The problem is that this should "just work" (yes, it's a contrived example, but clearly something like this occurred for someone or I would never have changed this):

	* [foo] 

	* [bar]


Breaking it causes confusion for people, which is  not what MultiMarkdown should do.

And while I understand that this worked well for you when exporting to LaTeX, it doesn't really mean anything in MultiMarkdown:

	- [w~1 =] **Fiction world (@):**
	    - [(1)] Sherlock Holmes does not exist.
	    - [(2)] Arthur Conan Doyle is the author of the fictional cases of Sherlock Holmes.

And you may be right -- they gain little, and you lose much.  But there are many more of "them"....  ;)

If you always want `[foo]` to be treated as a LaTeX argument, then what I would recommend is to simply modify your version of MultiMarkdown by replacing `\item{}` with `\item` in the source code and compile your own build.  This should revert the behavior back to MultiMarkdown-5 for you, without adversely affecting anyone else.

So now they lose nothing and you gain much.  Better math all the way around!


PS>  As a Sherlock fan (both as a reader and as a physician who appreciates the links between the detective and the physician) I am intrigued by the snippets of your thesis...  ;)

**Comment by mrkwnzl** [comment]
Since I usually use the MMD version that ships with Scrivener or Marked, I really hoped to get around compiling my own MMD version.

One last suggestion: Implementing a separate list for exactly this use case, using a different character as bullet points. I don’t know what character would be usable for this, maybe `%`, as those usually don’t come at the beginning of a line. Any obscure character would be okay for this. Example in MMD:
```
% [foo 1] bar

% [foo 2] bar
```
This would become this in LaTeX:
```
\begin{itemize}
\item [foo 1] bar
\item [foo 2] bar
\end
```
Other lists (including numbered lists) that are up until now being used (using `*` or `-` as bullet points), would render as currently in MMD6. Everybody wins, even the people who use Scrivener like I do. (I’m not the one who came up with that idea. I’ve read about in some “Using Scrivener with MMD” blog article.)

What do you think?

P.S.: My thesis is concerned with philosophy of language. This example illustrates problems with the semantic analysis of “Sherlock Holmes does not exist”, where the name “Sherlock Holmes” does not refer to any object, making it an empty name. That is a problem for some semantic analyses of “Sherlock Holmes does not exist”.

**Comment by fletcher** [comment]
The problem is that there is an exhaustive list of "if you could just add this one little thing" requests that I have received over the 13+ years that I have worked on MultiMarkdown.  If I had added them all, MMD would be a mess.

There are very few features of MMD that are of use for a single output format.  The beauty of Markdown was that all of the syntax was intuitively obvious without having to read any instructions.  The problem was that it was too limited for use much beyond blog posts and basic web pages.  My goal with MultiMarkdown was to expand Markdown to make it useful for a wider range of writers, adding features like footnotes and additional output formats.  This does mean an inevitable tradeoff between functionality and simplicity, and I have to strive for somewhere in the "sweet spot" with every feature I consider.

This particular feature seems a bit too "niche" to be a part of MMD proper.  At some point MultiMarkdown would transition from being a superset of Markdown to being a subset of LaTeX.  And that is not my goal for MultiMarkdown.

This feels like a case of fighting against the tools that are available, instead of working with them.  I would suggest looking into LaTeX to see whether `\itemize` can be overridden such that `\itemize{} [foo]` becomes `\itemize [foo]`.  LaTeX is flexible enough that this is *probably* possible and then you just need an extra line in your LaTeX configuration files.

Alternatively, and probably easier, would be to create a quick shell script (e.g. Perl) that uses regexp to convert `\itemize{} [foo]` to `\itemize [foo]` in your document, (or to just convert `\itemize{}` to `\item`).  Any of those can easily be made part of your workflow to give you the exact results you need.

**Comment by mrkwnzl** [comment]
I understand completely and actually really appreciate this attitude. 

So, one last idea. This time really, then I’ll let you alone with it, promise. With MMD6, I need to use the bibtex metadata to have proper citations in LaTeX. We could use something similar for labeled lists. Configure the metadata `latex-itemize: labeled` (or something similar). If configured, list items would be rendered without curly brackets. If not, the current behavior would prevail.

That way, MMD syntax stays untouched, and it wouldn’t exactly be a part of MMD proper, only part of LaTeX export. I don’t know if this could easily be implemented, but it would be elegant and non-intrusive, I think.

Thank you for considering this and putting up with me. It’s just such an elegant and powerful way to handle very complex lists in Scrivener and LaTeX that I’d really hate to lose it. But as I said, if you don’t like this solution, I won’t further push it.

(Just to comment briefly on the other solutions: I think it’s not an easy task to redefine this in LaTeX because `{}` means something very specific in LaTeX. So shell scripts and a forked MMD version would be my to go solutions. Both aren’t as elegant and easy, though, especially if used in conjunction with Scrivener.)

**Comment by fletcher** [comment]
I agree this is better.

It still bothers me to add a feature that intentionally breaks every format except LaTeX.  (In your example, should you decide to export to HTML for some reason, there would be this weird `[w~1 =]` in the middle of your list.  I'll think about it rather than just saying no....  But it "feels" like a step in the wrong direction.

You normally use a shell command to convert LaTeX to your final output format, right?  Just modify that to include your custom script.  Once done, you'll probably forget you even did this (until you migrate to a new machine and email me to ask why your MMD files stopped working.... ;)

**Comment by mrkwnzl** [comment]
> until you migrate to a new machine and email me to ask why your MMD files stopped working.... ;)

That’s what I’m afraid of, too.

Not to argue, but I don’t see how it breaks every other format. If you put `[w~1 =]` in a list, then that’s what you are getting, it’s just rendered a bit differently in LaTeX. Just to be clear, I think the HTML output should even with my proposed metadata option work just like it does right now.

I’m currently using this “syntax” also in my notes that I preview in HTML (using Marked 2). I’m using it for numbering example sentences, premisses in arguments, and definitions in my notes. Advantage is that I can use it in both my notes and still in my actual essays, without needing to convert it. It’s not the prettiest in HTML, but it get’s the work done, is readable, and renders nicely in LaTeX. I found no viable alternative.

But thank you very much for considering it!

**Comment by fletcher** [comment]
See additional discussion in #129.
