### ISSUE TITLE
Support LyX output?

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-6#13]

**Comment by fletcher** [comment]
Out of curiosity, how many people use the LyX functionality in MMD?

**Comment by jncomas** [comment]
On Mar 8, 2017, at 3:01 PM, Fletcher T. Penney <notifications@github.com> wrote:

> Out of curiosity, how many people use the LyX functionality in MMD?

Speaking from the humanities' side of the tracks, I do not. (In Academia, that's the poor side of the tracks, in case you were wondering.)

Best, 

JIm (in awe of your work)
-- 
Dr. James Comas
Associate Professor of English
Department of English, Box 70
Middle Tennessee State University
Murfreesboro, TN 37132
615-898-2606
http://capone.mtsu.edu/jcomas/
===========================

**Comment by jasedit** [comment]
I don't use LyX output at all - I use LaTeX extensively both personally and in projects integrating MMD.

**Comment by jemostrom** [comment]
Never used it, never used LaTeX either ... mostly because collaborators use LaTeX directly

**Comment by fletcher** [comment]
The author of the LyX code has moved away from it as well.  I am not opposed to including LyX code if someone wants me to do that -- but I won't write it myself as I don't use it and there doesn't seem to be a lot of demand.  In a similar vein, I'm happy to include RTF if someone writes that (no one has taken me up on that offer in the many years I've been saying it....  ;)

**Comment by ickc** [comment]
> no one has taken me up on that offer in the many years I've been saying it....

Should these "help wanted" kind of features be documented somewhere? If given more exposure to the "nice to have" feature but "help wanted", then in the end someone might actually do that.

**Comment by fletcher** [comment]
It's "documented" in multiple conversations on the discussion list, on my web site, probably on Twitter, and other places.  But not formally documented.

RTF is such a crappy format that I haven't worried too much about it.  ODF (FODT) -> RTF via LibreOffice is **much** better if you absolutely need an RTF file.

**Comment by fletcher** [comment]
I added a RTF issue to officially document my willingness to accept code that supports it.  ;)

**Comment by sallirom** [comment]
I use extensively the lyx output, it is my preferred output format, in fact.

I think I will have to stick to MMD v5  :(

I still love MMD

**Comment by fletcher** [comment]
Out of curiosity, why do you use LyX instead of LaTeX?

**Comment by sallirom** [comment]
Well, that's a fair question.

Short story? Out of laziness, I guess.

Long story:
I learnt how to use LaTeX in the nineties (1993 or 1994, I don't remember). That was the only decent way to produce beautiful math texts. Time passed and I no longer needed to do that. More time passed and I needed (had the time) to write again.

Then I discovered I was no longer proficient with LaTeX. I hated using tags and the act of writing was impeded with so much visual clutter; it was distracting for me. Since neither MD nor MMD had entered my life, I turned to LyX. You can focus on the content and it works like a charm if you have simple needs. 

Nowadays LyX sits on the end side of my workflow. I write using MMD or MD (I don't have a Mac, so sometimes I use [gingkoapp](https://gingkoapp.com/), sometimes [ghostwritter](https://github.com/wereturtle/ghostwriter)... or whatever comes handy) and then export to LyX. I can set the final looks with two _clics_ and then produce a good looking pdf. It is especially easy to refine the aspect of tables (long, short, whatever) and some other visuals.

I guess it is silly to stick to an old version of MMD, I will re-learn some LaTeX code and that's it.

I just LOVE MMD, it has made my life much easier. I have the utmost respect for your work. If you decide to drop LyX support, I understand it. I just wanted to point out that some people are very far away from using LaTeX. LyX is friendlier with newcomers, the learning curve is more gentle and the cognitive load of using it, much less.

Thanks for asking :)

**Comment by fletcher** [comment]
I never supported LyX -- another person used LyX a great deal, and volunteered to add support to MMD if I would include it in the main distribution.  So I did.  He no longer uses LyX as much, so did not have any interest in reworking it for MMD-6.  Which I understand.

I am not opposed to including it, but don't use LyX myself and have many other priorities demanding my time (e.g. MMD Composer for iOS.... ;) 

That said, I *am* experimenting with some ideas to see if I can speed up the process of adding additional output formats for MMD.  Certainly if that happens, I am not opposed to including LyX and RTF amongst those formats.


Thanks for the response!

**Comment by sallirom** [comment]
I understand you are talking about Charles R. Cowan, and of course, he must be credited for LyX support. I think both of you have been very generous. I see each release of open-sourced code as a gift: freely given, freely accepted. I totally understand your reasons (and his).

I'll keep an eye on future developments and I wish you luck and success with those ideas (and with MMD composer, although I am a linux user myself).
