### ISSUE TITLE
How to use Markdown styling in the metadata block?

### ISSUE THREAD

**Issue by halloleo** [fletcher/MultiMarkdown-6#175]
I use the following construct in many Markdown documents:

```
Title: Why 42 Is The Answer

# [%Title]

...
```

This works like charm: The main header shows the title as expected:

###  Why 42 Is The Answer

However when I decorate the title with markdown styles like

```
Title: Why `42` Is The Answer

# [%Title]

...
```

then the header does not show the markdown, but

###  Why \`42\` Is The Answer

How can I fix this? Do I somehow have to escape the decoration in the title?

Thanks for any pointers!

**Comment by fletcher** [comment]
1.  To be clear -- metadata variables work in MultiMarkdown.  They do not work in Markdown.

2. Metadata works for raw strings -- Multi/Markdown syntax is not supported inside the metadata values.  At this time I do not have plans to change this.

So, in this case, you have to "hard-code" the title in that header, rather than using a variable to represent it.

**Comment by halloleo** [comment]
Thanks for the details, Fletcher. 

Shame that Markdown in Metadata is not interpreted. Just curious: Why is this? After, all the  `[%Title]` syntax inserts the strings from the Metadata into the document...

**Comment by fletcher** [comment]
It has to do with when certain pieces of information are available during the processing steps, and avoiding recursive parsing.

From a more theoretical perspective, it's because the metadata holds key-value pairs of information, not markup.  If you find yourself putting "decoration" in the metadata, there's a good chance there is a better way to accomplish what you're trying.

**Comment by halloleo** [comment]
I understand. - If the title needs decoration it makes sense to repeat a decorated version in the text of the document and keep the metadata version of the title "clean".

**Comment by fletcher** [comment]
Exactly.  Also, if you really need decorated versions, you could have something like `title` and `title-latex`.
