### ISSUE TITLE
Fix Xcode warnings

### ISSUE THREAD

**Issue by nickasd** [fletcher/MultiMarkdown-6#179]
Are there any plans to address these warnings? I can do a PR if necessary, but I'm not sure about the last one. Can 2-4 be safely removed since they are not used?

<img width="409" alt="Schermata 2020-01-29 alle 15 38 04" src="https://user-images.githubusercontent.com/26737509/73365888-58835980-42ad-11ea-905e-91c31ad5f414.png">

**Comment by fletcher** [comment]
The top one has already been fixed (almost 2 months ago) -- be sure you are working from latest commits.

The last one is from `miniz.c` and is intentionally placed there by the author.  I do not intend to change this.

The remainder are in files that are automatically generated by `lemon`.  I do not intend to change lemon's source code.  Nor do I want to customize those files outside of the lemon processing workflow, because I want others to be able to verify that building those files themselves (e.g. by following the steps in the `update` shell script) end up with the same result.  If you see something that I missed that would tell lemon *not* to generate those variables that are then not used, please let me know.  

You, of course, can do whatever you like with your copy if seeing unnecessary warnings bothers you.

**Comment by nickasd** [comment]
Thank you for your prompt help. Indeed I thought I had updated but it wasn't the case. Ok, since you have no direct control over the remaining warnings, I decided to disable them by selecting the libMultiMarkdown target in the MultiMarkdown subproject, then setting `Build Settings > Inhibit all Warnings` to `Yes`.

**Comment by nickasd** [comment]
Right, sorry for that. I had forgotten that you already addresses those issues.
I had disabled the warnings at some point but they appeared again, probably after I regenerated the Multimarkdown .xcodeproj file. Disabling the warnings again didn't work some time ago, but I just tried again and it works now, so it could have been an Xcode issue that was solved in the meantime. Thanks for your patience.
