### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by LyesSaadi** [fletcher/MultiMarkdown-6#180]
Hi! I came across your incredible project, and for my own use, I packaged it for Fedora in [COPR](https://copr.fedorainfracloud.org/coprs/lyessaadi/multimarkdown/) (Collection Of Personal Repositories), which is a sort a building system where everyone can create easily its own RPM repos and packages.

To install it easily, just execute this:
```
sudo dnf copr enable lyessaadi/multimarkdown
sudo dnf install MultiMarkdown-6
```

I had to get rid of `/usr/bin/markdown` and `/usr/bin/mmd` (#165) as they conflict with other packages.

But, if COPR is pretty cool, it is better to have MultiMarkdown on the official repos. So, do you want me to submit it to the official Fedora Repos?

**Comment by fletcher** [comment]
You are welcome to submit it -- I don't have time to submit and maintain the package with various repositories, so feel free.

Thanks!

**Comment by LyesSaadi** [comment]
Hi !
Thanks for your approval, though, as per Fedora Policy, I have to ask you some questions:

1. **Naming:** Currently, the package is named MultiMarkdown-6, with the "6" being part of the package name because it's the name of the project, and apparently how OpenSUSE names it. Also in Fedora, packages are _Case Sensitive_, so trying to install `sudo dnf install multimarkdown` won't work. The Fedora Guidelines would recommend naming the package `multimarkdown` (or `multimarkdown6` if you want to have different versions available in the repos), but the final say is left to the maintainer. See [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/Naming/) for more about Fedora's package naming.

1. **Conflicts (this is a blocking issue):** Two installed binaries conflicts with two other packages: mtools for `/usr/bin/mmd`, this should be easily fixed by renaming `mmd` -> `mmd6` for example (maybe even the `mmd2*` -> `mmd62*` or `mmd6-2-*` for more consistency) and discount for `/usr/bin/markdown`, which is expected as discount is a markdown bash implementation, an alternative or an environment module might do the trick :slightly_smiling_face:. See [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/Conflicts/#_binary_name_conflicts) for more about that.

1. **Bundled libraries:** Is there a way to "unbundle" libraries (CuTest, argtable3, miniz and uthash), it doesn't seem so, as some seem to have been modified (I've only quickly looked into them), that is not a blocking issue, just not really great as some might have issues. But, if it's not the case, could you provide me with the version that you bundled if it's possible? Also, I can't find GLibFacade.c nor GLibFacade.h, is MultiMarkdown-4 really bundled or can I erase its reference?

**Comment by fletcher** [comment]
1. It seems that we would need to use `multimarkdown`, which would become `multimarkdown_6.x` if/when MultiMarkdown-7 is released.  (New major version numbers usually happen when there is a complete rewrite, and they truly are "new" projects that do not share a commit history in git, for example.  That is why they become new repositories as well.)

2. The scripts are not technically necessary and are merely convenience methods to reduce reliance on command line arguments.  They could be left for the user to install/customize as desired.  I don't have strong opinions on this.

3. From a programming perspective, these are not technically treated as separate libraries but instead are just part of the source like all the other source files.  There is no real reason to do anything other than build MultiMarkdown using the included files as is.  I will update them periodically when I think about it or when someone points out an improvement that has been made (to my knowledge there are no current bugs in any of them that lead to issues in MMD, though there are a couple of compiler warnings that can safely be ignored).  These are all basically single code/header file packages, and not worth treating as separate libraries from a source repository standpoint for this project.  Plus, this could introduce errors based on incompatibilities between versions without much of a benefit.  The goal with MMD was to have a single binary without any external dependencies that can be compiled on (basically) any hardware/OS desired.  The `multimarkdown` binary is all-inclusive.  There are no external dynamic libraries that must be installed on the machine so that MMD can function.  I specifically do *not* want to change that, as I hate being unable to simply copy small utility programs from one machine to another because of missing library requirements a mile long.  (I understand when the required libraries are *huge* that it is better to use a shared version than have 5 separate embedded copies of a 10 GB package, but these are relatively trivial from that perspective.)  Even internally, there is technically a static library named `libMultiMarkdown`, but this is simply embedded into the binary program and not used as a dynamic library.

4. `GLibFacade` was the precursor to `d_string` which was renamed as the code base changed, but the old name still lingers for historic reasons and to be clear that much of that work started with  work by Daniel Jalkut in the initial `peg-multimarkdown` version (aka MultiMarkdown 3).

**Comment by LyesSaadi** [comment]
Thanks for these answers !
I totally understand your views on libraries.

For the conflicts, do you want me to just remove `markdown` and `mmd` (or rename to `mmd6`) as I currently do? I can also create an alternative/environment module for markdown if you wish to, even if imo, It could create some confusion as they do not serve the same pupose (markdown and multimarkdown having some significant changes). But, I cannot choose myself, you are the maintainer.

**Comment by fletcher** [comment]
I think simplicity is probably best -- the scripts are really just an extra bonus.  `multimarkdown` is the real "meat" of the package.  It's reasonable to remove all of the scripts, or equally reasonable to just remove `markdown` and `mmd` and keep the others (e.g. `mmd2tex`).  I really have  no preference on this issue -- do what you like, or ask around, or see if anyone else comments here.

And I am the developer of MultiMarkdown, obviously, but you would be the maintainer of the Fedora package, basing it on the upstream project which is here.  ;)

**Comment by LyesSaadi** [comment]
I'll just remove the markdown and mmd scripts and ask the reviewer(s) what they do think of it.

Yes, I meant the upstream maintainer (=developer) :stuck_out_tongue: as opposed to downstream maintainer (the one who maintain the packages).

**Comment by LyesSaadi** [comment]
Bugzilla request here: https://bugzilla.redhat.com/show_bug.cgi?id=1801451 :)!
