### ISSUE TITLE
Suggestion: Use image title as figure caption when it exists

### ISSUE THREAD

**Issue by brief** [fletcher/MultiMarkdown-6#201]
Today, MultiMarkdown always uses an image's `alt` text as the caption in figures. So this Markdown:

```markdown
![Alt text](/path/to/img.jpg "Title text")
```

Results in this HTML:

```html
<figure>
  <img src="/path/to/img.jpg" alt="Alt text" title="Title text" />
  <figcaption>Alt text</figcaption>
</figure>
```

That's the right move when an image **only** includes alt text (`![Alt text](/path/to/img.jpg)`), but I believe captions should use the image title instead when one is included. So more like this:

```html
<figure>
  <img src="/path/to/img.jpg" alt="Alt text" title="Title text" />
  <figcaption>Title text</figcaption>
</figure>
```

This would be more in keeping with the [HTML standard's general guidelines ](https://html.spec.whatwg.org/multipage/images.html#general-guidelines) on alternative text, which say:

> ...the alt attribute's value should never contain text that could be considered the image's caption, title, or legend. It is supposed to contain replacement text that could be used by users instead of the image; it is not meant to supplement the image. The title attribute can be used for supplemental information.

And would hopefully be a non-breaking change for most users since title attributes have to be intentionally added to images (meaning users are making a distinction between `alt` and `title`).

What do you think?

**Comment by fletcher** [comment]
The metadata used for the caption is based on which support MultiMarkdown markup.

`![This can support **bold**](/path/img.jpg "This does not support bold")`

Since the caption and the title are generally distinct attributes of an image anyway, I'm not sure that either approach is technically correct.  There are trade-offs either way, but this allows for more detail in the caption, where it is needed, since markup should generally not be used in an image title.
