### ISSUE TITLE
How to correctly use transclusion?

### ISSUE THREAD

**Issue by nickasd** [fletcher/MultiMarkdown-6#234]
I'm using `mmd_string_convert` with the `EXT_TRANSLCUDE` option, but even when including a file with an absolute path like this: `{{/path/file.txt}}`, the output HTML just contains the string `{{/path/file.txt}}` instead of the contents of the file.txt file. I tried using a couple of different relative paths, but the official [documentation](https://fletcher.github.io/MultiMarkdown-6/syntax/transclusion.html) says that relative paths are relative to the file ... but what is this file when converting a string?

**Comment by fletcher** [comment]
If you're using `libMultiMarkdown` in your own program, you need to manage the transclusion before processing the text into HTML (or whatever format you choose).  You need to determine the appropriate path to the current file and current folder you want to use, and then use `mmd_transclude_source()` to perform the transclusion.

All of this is demonstrated in the `main()` function of `multimarkdown`.

**Comment by nickasd** [comment]
Thanks, I'm having a look at `main.c` right now. But there are a couple of things that confuse me and which I don't see documented anywhere. What's the use of `EXT_TRANSCLUDE` if I need to call that other function before? I see that there is also something going on with `EXT_CRITIC` and `EXT_COMPATIBILITY`, which I don't use personally, but it seems that simply passing those arguments to `mmd_string_convert` is not enough and I can't see a documentation about what one needs to do in order to correctly use those features.

**Comment by fletcher** [comment]
`EXT_TRANSCLUDE` could be used by your own code to control whether you enable or disable transclusion at any given time.  It is not otherwise required.  Transclusion and the CriticMarkup accept/reject features effectively modify the source text before it is processed by MultiMarkdown.

But again -- all of this is demonstrated by example in `main.c`.  If you're using `libMultiMarkdown` in your own different program, you have to provide the support for these features as demonstrated.  These features can be "expensive" to run, and may benefit from use-case specific optimization.  In the case of file transclusion, it also requires knowledge of and access to the file system, which otherwise `libMultiMarkdown` doesn't need.  Depending on your program, you may be using a real file system, or something else, and would need to manage file transclusion appropriately.

**Comment by nickasd** [comment]
I really appreciate your help and that you're offering this framework for free so that everyone can use it. But I also think that a little bit more explicit directions in the readme would greatly improve the adoption experience. When first trying to incorporate this into my Xcode project, I had a hard time gathering all the necessary information from the different github issues. And in this case for transclusion, it could easily be mentioned in the readme what function one has to call and what the arguments mean (it could even be extracted in a couple of sample code lines). Yes, one could take this all away by looking at `main.c`, but for someone who looks at it for the first time it can take quite a while to understand what's going on and what the important bits are. Having an index with the main features of the framework, or even only a sequence of paragraphs in which one can see what methods are available, would have saved me many hours; it's also a good starting point for someone who may want to contribute. Even the fact that `main.c` contains everything one needs to know is not mentioned in the readme. I don't want to complain or be ungrateful, because I'm very grateful for being able to adopt this framework; I just want to say that perhaps some users might be scared off and choose another solution if they have a difficult time or don't find any relevant documentation (that's what I might have done as well a few years ago).
