### ISSUE TITLE
Export from Ghostwriter via Multimarkdown 6.6.0 to odt format fails when image is included

### ISSUE THREAD

**Issue by jreed-cartago** [fletcher/MultiMarkdown-6#241]
I'm using the Ghostwriter software to write my MD and it provides an Export via Multimarkdown when it is installed. When I attempt to export my document I receive this error message when my document has an image embedded. 

![image](https://user-images.githubusercontent.com/72963764/184840329-31b1586e-aca9-4af6-8d9c-fe53f71f0510.png)

Yet it works correctly when I perform the export using the "OpenDocument Flat XML Format", or at least LibreOffice opens the file without problems.

I have attached below an example document written in [Ghostwriter 2.1.1](https://github.com/wereturtle/ghostwriter) and exported with Multimarkdown 6.6.0.

[image-failure-by-export.zip](https://github.com/fletcher/MultiMarkdown-6/files/9349350/image-failure-by-export.zip)

**Comment by fletcher** [comment]
I can't speak to Ghostwriter, since that is not my software.

When I use MultiMarkdown to convert the sample file to either fodt or odt, it seems to work just fine -- both files open within LibreOffice.

`multimarkdown -t fodt -o FODT.fodt`

`multimarkdown -t odt -o ODT.odt`


If you confirm that using those commands works, you may need to verify with the developer of Ghostwriter what is going on.

**Comment by jreed-cartago** [comment]
Thanks for the quick answer. Indeed manually calling this worked just fine. I'll go mention this to Ghostwriter as it must be on their end.

**Comment by fletcher** [comment]
My suspicion is that it relates to providing proper paths in order to embed the image.
