### ISSUE TITLE
Support Epub Output

### ISSUE THREAD

**Issue by nemesit** [fletcher/MultiMarkdown-6#26]
Proper support for epub with equivalents to Latex functionality like citations, footnotes, glossaries, abbreviations, tables etc. would make multimarkdown instantly the go to tool for epub creation. (at least for a rough version of a document).
With modern systems the need for LaTeX is declining rapidly while the demand for resizable modern documents rises all the time (think about all the iPads and similar devices)
PDF is a nice document format for printing but it is not really suitable for digital content consumption, especially since nobody uses adobe reader (which is the only tool that actually supports all pdf features).
With epub support one could easily create nice looking documents especially for scientific content. e.g. math via mathjax, code highlighting without issues etc. etc.
I believe mmd already does some basic epub output but a few LaTeX equivalents should be handled too, so that mmd's features get translated into a nice looking default.

**Comment by fletcher** [comment]
I had previously used a separate tool for converting MMD to EPUB  (<https://github.com/fletcher/MMD-ePub>).  It worked reasonably well, but was a bit tricky.

I added basic support to MMD 6 for directly creating EPUB documents.  So far, it has worked well for me (tested on MacOS, should work on Linux, not tested on Windows yet).   Currently, it only supports a single document -- nothing that requires extra files such as CSS, script files, images, etc.  Since MMD math is handled via LaTeX syntax, it does not directly work in EPUB files.    One could presumably use MathJax if the reader supports it, but it would be better to use MathML directly (I suspect.)  The QuickStart guide is now included as an EPUB document to demonstrate some of the features.
