### ISSUE TITLE
ctest - 3/8 Test #3: mmd-6-latex ......................***Failed

### ISSUE THREAD

**Issue by lucodealethea** [fletcher/MultiMarkdown-6#43]
Hi Fletcher,

I am kind of new in this topic., but I could compile successfully on Fedora 25. Still ctest
fails on mmd-6-latex test.

I had installed previously:
glibc-static
glibc-utils
Then, after test failure
3/8 Test #3: mmd-6-latex ......................***Failed

I installed 
latex-mk
latex2html
latexmk

Any thing to be worried about. Thx for this endeavour.

**Comment by fletcher** [comment]
`ctest -V` shows you more information about exactly what happened.  There was a bug in the `Fuzz` test in LaTeX that is fixed in the `develop` branch.

Otherwise, you should not need to install any dependencies forMMD-6.  It doesn't use glibc.  If you create LaTeX files, then of course you need a LaTeX system to process them, but MMD doesn't require that.
