### ISSUE TITLE
Update from 5.4 to 6.0 broke Scrivener MMD -> Latex output

### ISSUE THREAD

**Issue by edbucks** [fletcher/MultiMarkdown-6#46]
Under 6.0, Scrivener is no longer generating the start of its .tex file correctly. 

Correct version produced under 5.4:

`\input{mmd-scrivcustom-header}`
`\def\mytitle{My Great Novel}`
`\def\myauthor{Me}`
`\input{mmd-scrivcustom-begin-doc}`

6.0 is picking up the \defs from the Scrivener metadata, but omitting the \inputs.

Downgrading back to 5.4 solved the problem.

**Comment by fletcher** [comment]
I can't speak to how Scrivener handles MMD->LaTeX, so you'll have to take any Scrivener issues up with them.  The best way to distinguish is to test your files with MMD on the command line.

That said, MMD 6 handles LaTeX include file metadata differently.  See the QuickStart guide for details on the new metadata settings.  And since the guide itself is a MMD document, it serves as an example as well.  You'll see it uses a single metadata key to configure LaTeX, and it uses a more standardized naming convention for the mmd LaTeX files (which are also included in this repo)

Once you update your files to the new setup, I think you'll find it much easier to use.

**Comment by fletcher** [comment]
FYI -- I published additional information about LaTeX support in the QuickStart guide.  Currently on the develop branch only:

https://github.com/fletcher/MultiMarkdown-6/tree/develop/QuickStart

**Comment by edbucks** [comment]
Thanks!
