### ISSUE TITLE
multimarkdown -l <language> doesn't write lang attribute of tag <html>

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-6#51]
As the title says, no matter what is given on the commandline the document always contains `<html xmlns="http://www.w3.org/1999/xhtml" lang="en">`.

A further observation: In MMD 5 it was possible to define the language of the document in metadata with, for example `lang: de`. This seems to be ignored now.

**Comment by fletcher** [comment]
`language` is the metadata key to use, and it works.

The `-l <language>` option is actually for changing the built-in text that is used, e.g. `see footnote` and the like.

Metadata can use any valid or invalid string for the language.

The `-l` command line option is limited to the existing translations available in `i18n.h`.  I can make it so that using the `-l` option also sets the HTML `lang` attribute, but again that will be limited to a small subset of languages.

I am happy to accept translation pull requests for other languages.

**Comment by mn4367** [comment]
Ah, I see, thanks. Is there some documentation where these changes are listed?

Using `-l` also for the `lang` attribute would be consistent, I think. If there is no translation for it I'd just write it through anyway and use english for the built-in texts (like now).

**Comment by fletcher** [comment]
Partially documented, but not complete. I'll add it to the QuickStart guide.
