### ISSUE TITLE
Subscripts parsed wrong when not followed by a space

### ISSUE THREAD

**Issue by johnblommers** [fletcher/MultiMarkdown-6#70]
The following Markdown snippet typesets the formula for water,  then for Hydrogen:

```
H~2~O

H~2~
```

Process this as a snippet with MultiMarkdown 6.0.7:

```
multimarkdown -b -s -t html Math2.md
```

The resulting `Math2.html` file contains:

```
<p>H~2<sub>O</sub></p>

<p>H<sub>2</sub></p>
```

The formula for water is typeset incorrectly. Hydrogen is typeset correctly. This looks like a parsing error?

Let me type in the formula for water here:  H~2~O. The subscript 2 is striked through rather than subscripted. But strike through requires a pair of tilde characters around the text per the [guthub guide](https://guides.github.com/features/mastering-markdown/). Perhaps this is related?

**Comment by fletcher** [comment]
What's happening is that the trailing `~0` in the first example is an independent subscript.  For example, try `2~0` by itself.  This is analogous to `x^2`.

Because of this, the second `~` is unavailable for pairing with the first one.  I'll have to experiment -- during development there was an issue if I didn't handle the independent subscripts first, but I don't remember exactly what it was right now.  So I need to test different scenarios before trying a change.

**Comment by fletcher** [comment]
What I did was to change the order of the checks -- *if* the super/subscript is able to close, it means there is an earlier token of the same type within the same word.  In this instance, we disable the "shortcut"  syntax (e.g. `x^2`).  This means that each super/subscript must be wrapped in a pair of tokens.  This means that the first example below works, and the second doesn't:

    CH~3~CH~2~CH~2~CH~3~

    CH~3~CH~2~CH~2~CH~3

Thanks for pointing this out!

Fletcher
