### ISSUE TITLE
Xcode warnings

### ISSUE THREAD

**Issue by hlovatt** [fletcher/MultiMarkdown-6#72]
When building with Xcode I get the following warnings:

  1. parser.c line 708 unused variable engine expanded from ARG_FETCH
  2. token.c line 323 unused variable prev
  3. pub.c line 400 unused variable status
  4. parser.c line 174 code will never be executed
  5. transclude.c line 482 variable pars_stack may be uninitialised
  6. uuid.c line 136 implicit conversion loss unsigned long to unsigned int
  7. writer.c line 665 implicit conversion loss unsigned long to int

You may well know about all these and they are all potentially OK. Thought I would log them incase they are helpful.

Great work, thanks, -- Howard.

**Comment by fletcher** [comment]
None of those seem to be "legitimate" warnings, so I think all is still good.

Thanks for checking in!!

**Comment by nickasd** [comment]
I also noticed that there are 3 warnings "unused variable engine", plus "Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.". What do you mean when you say that they are not legitimate?

**Comment by fletcher** [comment]
They don't have any actual bearing on the accuracy/stability of the code.

**Comment by nickasd** [comment]
And those unused variables cannot be deleted?

**Comment by fletcher** [comment]
@nickasd -- As I commented the last time you asked (#179 ), these files are automatically generated.  You are welcome to review the code of `lemon` and generate fixes that strip out unused variables and attempt to get those fixes accepted by the developer(s).

I do not have the time to do that since they are not truly bugs.  You can modify your xcode project to disable warnings on unused variables (I will not do that because it is a helpful warning some of the time) -- I thought you said you had done this already, so you should no longer be seeing these warnings?  You could also conceivably write a shell script to comment out the specific variable declarations after the files are generated, but I suspect it would be faster to simply do it by hand.

I won't reject a pull request that disables unused variables, but I will also not commit to maintaining that myself.  So whenever those files get re-generated, the unused variables will reappear and they will have to be removed again.

**Comment by nickasd** [comment]
Right, sorry for that. I had forgotten that you already addresses those issues.
I had disabled the warnings at some point but they appeared again, probably after I regenerated the Multimarkdown .xcodeproj file. Disabling the warnings again didn't work some time ago, but I just tried again and it works now, so it could have been an Xcode issue that was solved in the meantime. Thanks for your patience.

**Comment by fletcher** [comment]
No worries!  :)
