### ISSUE TITLE
Swift package fails to compile

### ISSUE THREAD

**Issue by arennow** [fletcher/MultiMarkdown-6#77]
When attempting to build Multimarkdown as a Swift Package Manager package, I get first an error that 

```
Marker/.build/checkouts/MultiMarkdown-6.git-1322455500340203929/Sources/libMultiMarkdown/i18n.h:107:20: fatal error: bracket nesting level exceeded maximum of 256
        unsigned long h = HASH(x);
                          ^
```

And, when compiling with `swift build -Xcc -fbracket-depth=512` to get past that error, a further issue that

```
Marker/.build/checkouts/MultiMarkdown-6.git-1322455500340203929/Sources/libMultiMarkdown/mmd.c:75:10: fatal error: 'version.h' file not found
#include "version.h"
         ^
```

**Comment by arennow** [comment]
[Marker.zip](https://github.com/fletcher/MultiMarkdown-6/files/1203458/Marker.zip)

**Comment by fletcher** [comment]
I haven't tried compiling for Swift in quite a while -- the config will need to be modified for subsequent changes to the project.  

The bracket depth is the first one, and needs to be incorporated into `CMakeLists.txt`, so that `version.h` is build and able to be included.

I'll get to it eventually, but not sure when.  I don't need Swift at the moment and have a bunch of other things on my to-do list in front of it.

**Comment by fletcher** [comment]
See <https://github.com/fletcher/MultiMarkdown-6/issues/89>
