### ISSUE TITLE
Enhancement: Deprecate & Remove "Transclude Base"

### ISSUE THREAD

**Issue by bdkjones** [fletcher/MultiMarkdown-6#79]
I realize this is probably a losing fight, but I'm suggesting that the `Transclude Base` metadata feature be formally deprecated in MMD6 and removed in a future version. 

## Why?

This feature is a bad one and should have been rejected when proposed. Consider an MMD document with 500 lines and on line 450 we write:

`{{someFile}}`

We think: "Ah, we're importing a `someFile.mmd` document that's located next to the file we're editing."

Except we're not. Because 449 lines above, there's a stupid `Transclude Base: /some/other/folder`. So it's going to take us a hot minute to figure out where the hell `someFile` is located, since we have to now find the `Transclude Base` parameter and merge the two paths. This is especially mystifying if you're not aware that `Transclude Base` is even a thing you should be looking for. 

There's no logical reason to allow splitting the import path between two different spots. Even if we have to write multiple imports, it's FAR better to do this:

    {{some/other/folder/someFile}}
    {{some/other/folder/file2}}
    {{some/other/folder/file3}}

than it is to factor out the leading path and then stick that hundreds of lines away from the import statements it affects. The `Transclude Base` parameter is for lazy programmers who would sacrifice code-clarity for the sake of a few copy-paste commands.

I propose that MMD emphasize clarity and readability over saving a few keystrokes.

**Comment by fletcher** [comment]
Thanks for the input, and for taking the time to write out your thoughts.

You certainly don't have to use the `Transclude Base` metadata.  And if your needs are quite simple, you'll never have to.  

The example you provide is a trivial example that doesn't make use of the feature.  I can't tell you why the author decided to split the paths -- you'll have to ask them.

But if you are creating complex documents with multiple levels of transclusion, it is a necessity.  For example, creating a book comprised of multiple chapters, each of which consists of multiple subchapters, each of which includes its own directory for images, etc.  You have to be able to disambiguate `chapter1/images` from `chapter2/images`, etc.  `Transclude Base: .` allows you to do that.

You could avoid this if *every* transclusion used absolute paths, but that requires an identical path structure for every machine that the document is compiled on.  Not a reasonable requirement unless you're a solo author with a single computer to work from.  And you could never decide to move your project to a different location on that computer.

And even then, you would lose the flexibility of being able to transclude different files based on whether a given file is the "master" file, or is, itself, being transcluded.  This is useful for creating separate documents for each chapter, as well as a single document concatenating all chapters.  You might want different headers/footers/etc. in this situation.

> The Transclude Base parameter is for lazy programmers who would sacrifice code-clarity for the sake of a few copy-paste commands.

Just because you don't understand something doesn't mean it's for lazy people...  ;)  Once you start creating complex projects with multiple outputs from reusable inputs, you'll find that you can't reasonably do it without this feature.

**Comment by bdkjones** [comment]
I can definitely understand there may be use-cases where changing the base-path of imports may be useful. 

But even so, the current implementation is not good because it separates the path into two parts, often separated by a great deal of text. It obfuscates intent and harms readability—both for folks besides the author AND for the author themselves, who will come back to MMD files they wrote a long time ago and forget that there's a mess of transclude base paths going on.

### Recommendation:

Instead of removing the feature, modify it to eliminate the current weaknesses in the implementation. As an example, consider how Sass allows you to interpolate variables into an `@import` path:

    $myVar = 'some/folder/path'
    ...
    @import '{$myVar}/someFile';

Here, the "base" path is defined only once and assigned to a variable, which is then used in the `@import` statement to construct the full path to the imported file. 

A similar approach for MMD would retain all of the benefits of "Transclude Base", but ALSO make it very clear that the path to the imported file is one constructed of multiple parts. This is a far superior implementation of the concept, for that reason alone.

**Comment by bdkjones** [comment]
A possible starting point for a similar approach in MMD could be something like this:

    Transclude Base: some/folder/path
    ...
    ...
    {{{base}/someFile}}

If `Transclude Base` is not defined, then `{base}` becomes a no-op, which retains all of the current behavior BUT provides much greater clarity into how this path is structured.

**Comment by fletcher** [comment]
I get that you don't agree with the use of the `Transclude Base` metadata as an optional way to ensure proper handling of nested transclusion, but making the situation more complex doesn't seem to me to be a step in the right direction.

Most people should probably not be using `TB` metadata, but when used it's implicitly included in the transclusion path, just like `Base Header Level` is implicitly added to the header depth without using something like `{base}# Some Header #`.  Precedent for this approach exists in the HTML `<base href="foo">` construct.

**Comment by bdkjones** [comment]
Fair enough, thanks!

**Comment by fletcher** [comment]
I do appreciate the feedback, even if I don't agree with it.  ;)
