### ISSUE TITLE
HTML comments containing empty lines are processed as Markdown text

### ISSUE THREAD

**Issue by christophberger** [fletcher/MultiMarkdown-6#96]
I observed this only recently, so this might be a new issue in MMD 6.2.2:

Run

    multimarkdown -b -s -t html <filename>.md

on the following text, and the result contains the last HTML comment processed as if it was standard text.

```
# Markdown with HTML

This is normal text.

<!-- This is a single-line HTML comment. -->

<!-- This is a multi-line HTML comment
with no empty lines.
-->

<!-- This is a multi-line HTML comment

with empty lines.

-->
```

Output:

```
<h1 id="markdownwithhtml">Markdown with HTML</h1>

<p>This is normal text.</p>

<!-- This is a single-line HTML comment. -->

<p><!-- This is a multi-line HTML comment
with no empty lines.
--></p>

<p>&lt;!&#8211; This is a multi-line HTML comment</p>

<p>with empty lines.</p>

<p>&#8211;&gt;</p>
```

**Comment by fletcher** [comment]
Correct -- blank lines separate paragraphs, so each paragraph includes only a fragment of the comment.  This causes each fragment to be treated separately.

This has been the case since the first version of MMD-6.

It may or may not be possible to allow blank lines inside HTML comments (without a major overhaul of the parser, or without adding a separate parse up front that would slow things down).  My suspicion is that it's not, and it's a low priority either way.  I'll try and take a look when I get a chance

**Comment by christophberger** [comment]
Thank you for looking into this. 

Regarding priority, this issue caused a comment to appear on a Web page inside an online course that is already open for students, until I noticed this and removed the comment manually from the output.

The background story is, I create course lectures from markdown files, and I tend to add the first Brainstorms as an HTML comment to those files, as well as quizzes that I must manually insert into the lecture when composing the lecture on the course platform. Now chances are that both kinds of comments may contain quite some blank lines.

I can remove the brainstorm comments, but I would like to be able to keep the quizzes as invisible comments in the file, just in case I have to migrate everything to another course platform.

Or would there be a suitable alternative to using HTML comments for the purpose of keeping invisible data inside a markdown document?

**Comment by fletcher** [comment]
1. I should clarify -- it's a low priority for me in terms of MMD development.  I don't mean that it's a low priority for any particular user, such as yourself.  ;)  Clearly it would be a high priority for you. 

(That said, if the content was in an HTML comment in a Markdown file, wasn't the content included on the web page already, just not visible unless someone checked the web page source?  I definitely would not recommend using HTML comments as a way of keeping any information private, regardless of which Markdown engine you use.)

2. The way I would consider approaching your quizzes would be to keep them as separate files, and use transclusion to pull them into the master file.  Transclusion can be turned on/off as needed via command line arguments.

3. To be clear, I'm not arguing that this is the "right" way to handle HTML comments with blank lines.  It's just a (potentially) unavoidable side effect of the MMD-6 parsing strategy.  Everything else about the MMD-6 parser I have been happy with, particularly the speed.

(Continuing the stream of consciousness response...)

4. Discussing this made me think of an idea, then in experimenting realized I had already implemented it....  ;)   Keep the HMTL comment start (i.e. `<!--`)  on a line by itself.  Everything until the comment close, OR the end of the document if the comment is not closed, will be treated as a comment.

5. So I guess this actually had faster than light priority, since a solution was implemented before your request.  ;)

**Comment by christophberger** [comment]
Tested and confirmed! Keeping the comment start on a line by itself eliminates the issue. 

I totally understand your priorities as well as the difficulties that come with the new MMD-6 way of parsing the document. I can live with the suggested solutions, so it's fine with me if you want to close this issue.

About private data, the students do see the quizzes anyway at the end of the lecture, so looking into the source would not reveal anything new :)  But I know what you mean, in general it would be silly trying to hide information by just not rendering it.

**Comment by fletcher** [comment]
I'll leave this open for now.  I might be able to tweak the source so that the comment start doesn't have to be by itself, but it will still have to be the first thing in a paragraph.

Glad it worked for you!

**Comment by fletcher** [comment]
I experimented a bit and updated the test suite directory with additional examples of things that are and are *not* HTML comments.

Basically, the current approach is consistent with other structures in MMD-6 (namely HTML Blocks and, to a lesser extent, fenced code blocks.)

`<!--` on a line by itself opens a "HTML Comment Block".  Everything following it will be a comment until a `-->` on a line by itself, or until the end of the document. 

`<!--` at the beginning of a line that has other content opens a "HTML Comment Span".  The span must start and end inside a paragraph block.

This is the same behavior used for other html constructs.

The `HTML Blocks` and `HTML Comments` test suites demonstrate various examples.

I experimented with allowing `!<-- foo` to start a comment block, but then one would expect to be able to close it on a subsequent line with `bar -->`.  This would require a more redundant parsing process, so I stuck with the original behavior of requiring `!<--` to be on a line by itself.

Hopefully this explains things, but the test suite is the best way to see examples of what does and does not work.
